<?php

namespace gesBarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * lineaCreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lineaCreditoRepository extends EntityRepository
{
}
